### ISSUE TITLE
Thông tin người dùng

### ISSUE THREAD

**Issue by TTTThanh2812** [TTTThanh2812/SE104.N27.CLC#12]

**Comment by thuong22092k3** [comment]
[Mô tả màn hình thông tin người dùng.docx](https://github.com/TTTThanh2812/SE104.N27.CLC/files/11458521/Mo.t.man.hinh.thong.tin.ng.i.dung.docx)

**Comment by thuong22092k3** [comment]
Chỉnh sửa trang wiki [Thông tin người dùng](https://github.com/TTTThanh2812/SE104.N27.CLC/wiki/4.1.4-Th%C3%B4ng-tin-ng%C6%B0%E1%BB%9Di-d%C3%B9ng)
