### ISSUE TITLE
Thông tin khách hàng

### ISSUE THREAD

**Issue by TTTThanh2812** [TTTThanh2812/SE104.N27.CLC#17]

**Comment by TTTThanh2812** [comment]
[Danh sách khách hàng và thông tin khách hàng](https://github.com/TTTThanh2812/SE104.N27.CLC/wiki/Kh%C3%A1ch-h%C3%A0ng-v%E1%BB%9Bi-web-admin)

**Comment by thuong22092k3** [comment]
[Chỉnh sửa trang wiki khách hàng](https://github.com/TTTThanh2812/SE104.N27.CLC/wiki/4.1.4-Th%C3%B4ng-tin-ng%C6%B0%E1%BB%9Di-d%C3%B9ng)
