### ISSUE TITLE
Thông tin từng thể loại

### ISSUE THREAD

**Issue by Tlyl1111** [TTTThanh2812/SE104.N27.CLC#22]

**Comment by Tlyl1111** [comment]
[Thông tin từng thể loại](https://github.com/TTTThanh2812/SE104.N27.CLC/wiki/Th%C3%B4ng-tin-t%E1%BB%ABng-th%E1%BB%83-lo%E1%BA%A1i)

**Comment by thuong22092k3** [comment]
Chỉnh sửa trang wiki [Thông tin từng thể loại](https://github.com/TTTThanh2812/SE104.N27.CLC/wiki/6.-Th%C3%B4ng-tin-t%E1%BB%ABng-th%E1%BB%83-lo%E1%BA%A1i)

**Comment by thuong22092k3** [comment]
Sửa ảnh trong trang wiki [Thông tin từng thể loại](https://github.com/TTTThanh2812/SE104.N27.CLC/wiki/6.-Th%C3%B4ng-tin-t%E1%BB%ABng-th%E1%BB%83-lo%E1%BA%A1i)

**Comment by thuong22092k3** [comment]
Sửa lại trang wiki [Tùy chọn](https://github.com/TTTThanh2812/SE104.N27.CLC/wiki/6.1-T%C3%B9y-ch%E1%BB%8Dn) trong trang  [Thông tin từng thể loại](https://github.com/TTTThanh2812/SE104.N27.CLC/wiki/6.-Th%C3%B4ng-tin-t%E1%BB%ABng-th%E1%BB%83-lo%E1%BA%A1i)

**Comment by thuong22092k3** [comment]
Thêm DFD cho [Thanh tìm kiếm](https://github.com/TTTThanh2812/SE104.N27.CLC/wiki/6.2-Thanh-t%C3%ACm-ki%E1%BA%BFm) trong trang [Thông tin từng thể loại](https://github.com/TTTThanh2812/SE104.N27.CLC/wiki/6.-Th%C3%B4ng-tin-t%E1%BB%ABng-th%E1%BB%83-lo%E1%BA%A1i)
