### ISSUE TITLE
Trang chủ

### ISSUE THREAD

**Issue by TTTThanh2812** [TTTThanh2812/SE104.N27.CLC#7]

**Comment by Tlyl1111** [comment]
https://github.com/TTTThanh2812/SE104.N27.CLC/wiki/Trang-ch%E1%BB%A7-kh%C3%A1ch-h%C3%A0ng

**Comment by Tlyl1111** [comment]
[https://github.com/TTTThanh2812/SE104.N27.CLC/wiki/Trang-ch%E1%BB%A7-kh%C3%A1ch-h%C3%A0ng](url)

**Comment by Tlyl1111** [comment]
[Trang chủ khách hàng](https://github.com/TTTThanh2812/SE104.N27.CLC/wiki/Trang-ch%E1%BB%A7-kh%C3%A1ch-h%C3%A0ng)
