### ISSUE TITLE
Thể loại

### ISSUE THREAD

**Issue by TTTThanh2812** [TTTThanh2812/SE104.N27.CLC#8]

**Comment by Tlyl1111** [comment]
[Thể loại](https://github.com/TTTThanh2812/SE104.N27.CLC/wiki/Th%E1%BB%83-lo%E1%BA%A1i)

**Comment by thuong22092k3** [comment]
Chỉnh sửa trang wiki [Thể loại](https://github.com/TTTThanh2812/SE104.N27.CLC/wiki/5.-Th%E1%BB%83-lo%E1%BA%A1i)

**Comment by thuong22092k3** [comment]
Sửa lại ảnh trang wiki [Thê loại](https://github.com/TTTThanh2812/SE104.N27.CLC/wiki/5.-Th%E1%BB%83-lo%E1%BA%A1i)
