### ISSUE TITLE
Thông tin từng board game

### ISSUE THREAD

**Issue by TTTThanh2812** [TTTThanh2812/SE104.N27.CLC#9]

**Comment by Tlyl1111** [comment]
[Thông tin từng boardgame](https://github.com/TTTThanh2812/SE104.N27.CLC/wiki/Th%C3%B4ng-tin-t%E1%BB%ABng-Boardgame)

**Comment by thuong22092k3** [comment]
Chỉnh sửa trang wiki trang [Thông tin từng Boardgame](https://github.com/TTTThanh2812/SE104.N27.CLC/wiki/6.3.-Th%C3%B4ng-tin-t%E1%BB%ABng-Boardgame)

**Comment by thuong22092k3** [comment]
Sửa ảnh và thông tin trong trang wiki [Thông tin từng boardgame](https://github.com/TTTThanh2812/SE104.N27.CLC/wiki/6.3.-Th%C3%B4ng-tin-t%E1%BB%ABng-Boardgame)
